version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:80
    volumes:
      - './src:/workspace/src'
    restart: on-failure
